import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Timer from "../components/timer";
import OffsetTimer from "../components/offsetTimer";
import Offsetter from "../components/offsetter";
import Globalizer from "../components/globalizer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a> <em>(now MobX flavored!)</em>
        </h1>

        <Timer />
        <OffsetTimer />
        <Offsetter />
        <Globalizer />
      </main>
    </div>
  )
}
